name: Testing
on: [push]

jobs:
    test:
        name: Testing
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                julia-version: ['1.3.0']
                julia-arch: [x64, x86]
                exclude:
                    - os: macos-latest
                      julia-arch: x86
        steps:
            - uses: actions/checkout@v1.0.0
            - name: "Set Up Julia"
              uses: julia-actions/setup-julia@latest
              with:
                  version: ${{ matrix.julia-version }}
                  arch: ${{ matrix.julia-arch }}
            - run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test()'
